name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
    - main
    

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: upload-artifact@v4
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ github.token }}
